pairs = [  
                /*          céu                                   terra                            trovão                                             água                                  montanha                                                                madeira                       fogo                                 lago               */
  /* céu -----*/ ["céu", "céu", "Ch'ien - O criativo"],["terra", "céu", "T'ai - Paz"],["trovão", "céu", "Ta Chuang - O Poder do Grande"],["água", "céu", "Hsu - A Espera"],["montanha", "céu", "Ta Ch'u - O Poder de Domar do Grande"],["madeira", "céu", "Hsiao Ch'u - O Poder de Domar do Pequeno"],["fogo", "céu", "Ta Yu - Grandes Posses"],["lago", "céu", "Kaui - Irromper"],
  /* terra ---*/ ["céu", "terra", "Pi - Estagnação"],["terra", "terra", "K'un - O Receptivo"],["trovão", "terra", "Yu - Entusiasmo"],["água", "terra", "Pi - Manter-se Unido"],["montanha", "terra", "Po - Desintegração"],["madeira", "terra", "Kuan - Contemplação"],["fogo", "terra", "Chin - Progresso"],["lago", "terra", "Ts'ui - Reunião"],
  /* trovão --*/ ["céu", "trovão", "Wu Wang - Inocência"],["terra", "trovão", "Fu - Retorno"],["trovão", "trovão", "Chên - O Incitar "],["água", "trovão", "Chun - Dificulade Inicial"],["montanha", "trovão", "I - As Bordas da Boca"],["madeira", "trovão", "I - Aumento"],["fogo", "trovão", "Shih Ho - Morder"],["lago", "trovão", "Sui - Seguir"],
  /* água ----*/ ["céu", "água", "Sung - Conflito"],["terra", "água", "Shih - O Exército"],["trovão", "água", "Hsieh - Liberação"],["água", "água", "K'an - O Abismal"],["montanha", "água", "Meng - Insensatez Juvenil"],["madeira", "água", "Huan - Dispersão"],["fogo", "água", "Wei Chi - Antes da Conclusão"],["lago", "água", "K'un - Opressão"],
  /* montanha */ ["céu", "montanha", "Tun - A Retirada"],["terra", "montanha", "Ch'ien - Modéstia"],["trovão", "montanha", "Hsiao Kuo - A Preponderância do Pequeno"],["água", "montanha", "Chien - Obstrução"],["montanha", "montanha", "Kên - A Quietude"],["madeira", "montanha", "Chien - Desenvolvimento"],["fogo", "montanha", "Lü - O Viajante"],["lago", "montanha", "Hsien - A Influência"],
  /* madeira -*/ ["céu", "madeira", "Kou - Vir ao Encontro"],["terra", "madeira", "Chêng - Ascensão"],["trovão", "madeira", "Heng - Duração"],["água", "madeira", "Ching - O Poço"],["montanha", "madeira", "Ku - Trabalho Sobre o que Se Deteriorou "],["madeira", "madeira", "Sun - A Suavidade"],["fogo", "madeira", "Ting - O Caldeirão"],["lago", "madeira", "Ta Kuo - A Preponderâcia do Grande"],
  /* fogo ----*/ ["céu", "fogo", "Tung Jên - Comunidade com os Homens"],["terra", "fogo", "Ming I - O Obscurecimento da Luz"],["trovão", "fogo", "Fêng - Abundância"],["água", "fogo", "Chi Chi - Após a Conclusão"],["montanha", "fogo", "Pi - Graciosidade "],["madeira", "fogo", "Chia Jen - A Família"],["fogo", "fogo", "Li- Aderir"],["lago", "fogo", "Ko - Revolução"],
  /* lago ----*/ ["céu", "lago", "Lu - A Conduta"],["terra", "lago", "Lin - Aproximação"],["trovão", "lago", "Kuei Mei - A Jovem que se Casa"],["água", "lago", "Chieh - Limitação"],["montanha", "lago", "Sun - Diminuição"],["madeira", "lago", "Chung Fu - Verdade Interior"],["fogo", "lago", "K'uei - Oposição"],["lago", "lago", "Tui - A Alegria"],
    
]  